function(message)
  if (teuthid_message_switch)
    if (MessageType STREQUAL FATAL_ERROR OR MessageType STREQUAL SEND_ERROR OR
      MessageType STREQUAL WARNING OR MessageType STREQUAL AUTHOR_WARNING OR
      MessageType STREQUAL STATUS)
      list(GET ARGV 0 MessageType)
      list(REMOVE_AT ARGV 0)
    endif()
    _message(${MessageType} ${ARGV})
  endif(teuthid_message_switch)
endfunction(message)

string(ASCII 27 Esc)
set(ColorReset  "${Esc}[m")
set(ColorBold   "${Esc}[1m")
set(Red         "${Esc}[31m")
set(Green       "${Esc}[32m")
set(Yellow      "${Esc}[33m")
set(Blue        "${Esc}[34m")
set(Magenta     "${Esc}[35m")
set(Cyan        "${Esc}[36m")
set(White       "${Esc}[37m")
set(BoldRed     "${Esc}[1;31m")
set(BoldGreen   "${Esc}[1;32m")
set(BoldYellow  "${Esc}[1;33m")
set(BoldBlue    "${Esc}[1;34m")
set(BoldMagenta "${Esc}[1;35m")
set(BoldCyan    "${Esc}[1;36m")
set(BoldWhite   "${Esc}[1;37m")

macro(msg_status msg_ colorized_msg_)
  message(STATUS "${msg_}${Green}${colorized_msg_}${ColorReset}")
endmacro()

macro(msg_warning msg_)
  message(STATUS "WARNING: ${msg_}")
endmacro()
macro(msg_error msg_)
  message(STATUS "ERROR: ${msg_}")
  message(FATAL_ERROR "")
endmacro()
